### PR TITLE
fix: rocksdb-cache doesn't compile

### PR DESCRIPTION
**Pull request by remoe**

### CODE REVIEW

**Comment by remoe** [comment]
This is fixed as well by #1568 . Can someone please merge/fix this?

**Comment by gwaldron** [comment]
Merged #1568 please try that.

**Comment by GouShiQuan** [comment]
unsubscribe



在 2020-11-17 02:32:51，"Remo E" <notifications@github.com> 写道：

Closed #1600.

**Comment by GouShiQuan** [comment]
unsubscribe



At 2020-11-17 02:13:05, "Glenn" <notifications@github.com> wrote:

Merged #1568 please try that.

**Pull request closed without merging**
