### PR TITLE
Rex SharedGeometry: Refactor draw primitives implementation to fix ATI rendering issues with older drivers.

### PR DESCRIPTION
**Pull request by emminizer**

### CODE REVIEW

**Comment by gwaldron** [comment]
Merging prior to 3rd party app testing. If there's an issue we may revisit

**Comment by remoe** [comment]
@emminizer , how was the behavior of this rendering issues?

**Comment by emminizer** [comment]
@remoe We have been getting reports for the last several months from users who can no longer view the globe. These were all users with older cards (e.g. Matrox C420 with 22.19.693.256 driver, AMD Radeon HD 7730M) that were experiencing this issue. Drivers were as upgraded as they could get (newer drivers don't support older card).

The symptom manifested essentially as a blank, black globe. With the simple sky model enabled, we could see the lighting along the edge of the globe, but no texture data. We could add things like line features onto the globe and they were drawn correctly, it was just the underlying globe imagery data that wasn't rendering. This used to work on software releases 9+ months back.

We were able to generate API Trace output from a failing laptop. When running the replay through API Trace, the display was incorrect when run on the AMD Radeon HD 7730M. But when we ran the exact same trace file through API Trace on systems with other cards, everything was looking fine.

Current belief is that there's something funky with the VAO state and EBO that isn't being captured by these older cards, forcing a requirement to generate and rebind it each time.

**Comment by remoe** [comment]
@emminizer thanks for this detailed explanation! We have similarly (VAO) issues with MacOSX:
https://github.com/gwaldron/osgearth/issues/1703

**Comment by emminizer** [comment]
Oh! Yes that very likely could be the same issue we were seeing. I had not seen that issue previously.

**Pull request merged**
