### PR TITLE
compile fix for gcc with osg built with double bounding boxes

### PR DESCRIPTION
**Pull request by jklimke**

### CODE REVIEW

**Comment by gwaldron** [comment]
What/where is the compiler error?

**Comment by jklimke** [comment]
The error was caused due to a call to std:max 

/opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp: In member function ‘virtual osg::Node* SimpleModelSource::createNodeImplementation(const osgEarth::Map*, osgEarth::ProgressCallback*)’:
/opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:233:83: error: no matching function for call to ‘max(osg::BoundingSphereImpl<osg::Vec3d>::value_type, float&)’
                     plod->setRadius(std::max(result->getBound().radius(), maxRange));
                                                                                   ^
/opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:233:83: note: candidates are:
In file included from /usr/include/c++/4.8/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.8/ios:40,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/local/include/osg/Notify:20,
                 from /opt/wvs/build/libs/osgearth/src/osgEarth/Notify:24,
                 from /opt/wvs/build/libs/osgearth/src/osgEarth/Common:24,
                 from /opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelOptions:22,
                 from /opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:20:
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note:   template argument deduction/substitution failed:
/opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:233:83: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘float’)
                     plod->setRadius(std::max(result->getBound().radius(), maxRange));
                                                                                   ^
In file included from /usr/include/c++/4.8/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.8/ios:40,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/local/include/osg/Notify:20,
                 from /opt/wvs/build/libs/osgearth/src/osgEarth/Notify:24,
                 from /opt/wvs/build/libs/osgearth/src/osgEarth/Common:24,
                 from /opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelOptions:22,
                 from /opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:20:
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note:   template argument deduction/substitution failed:
/opt/wvs/build/libs/osgearth/src/osgEarthDrivers/model_simple/SimpleModelSource.cpp:233:83: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘float’)
                     plod->setRadius(std::max(result->getBound().radius(), maxRange));
                                                                                   ^
make[2]: *** [src/osgEarthDrivers/model_simple/CMakeFiles/osgdb_osgearth_model_simple.dir/SimpleModelSource.cpp.o] Error 1
make[1]: *** [src/osgEarthDrivers/model_simple/CMakeFiles/osgdb_osgearth_model_simple.dir/all] Error 2

**Comment by gwaldron** [comment]
OK. Probably better just to cast maxRange to (BoundingSphere::value_type) in the std::max call.

**Comment by jklimke** [comment]
Ah sorry, i was searching for that kind of solution, but i could not see that declaration. It is a lot better this way. Thank you.

**Pull request closed without merging**
