### PR TITLE
GL_LIGHTING mode no longer set if FFP not available.  Now consistentl…

### PR DESCRIPTION
**Pull request by emminizer**
…y setting OE_LIGHTING_DEFINE.

### CODE REVIEW

**Comment by emminizer** [comment]
I had attempted to do this automatically in ShaderGenerator but couldn't get it to consistently remove all the GL_LIGHTING flags that osgEarth was using/generating in GL3/No-FFP mode.

After this patch, I am no longer getting any lighting-related invalid enumeration errors in GL 3.3.

**Comment by emminizer** [comment]
After some more research, it might be the case that we can drop this and replace with a single call to osg::State's setModeValidity(GL_LIGHTING, false).  This would need to be done for every graphics context.  I haven't tested it out yet but it might be a cleaner path forward.

**Comment by gwaldron** [comment]
Apparently that setting's been there for 12 years .. first I've heard of it :)

**Comment by gwaldron** [comment]
Dan, I took a different approach to the same issue. Closing this PR. Thanks.

**Comment by emminizer** [comment]
No problem, I understand and agree with the approach I see you're taking.  Sounds good.

**Pull request closed without merging**
